baseURL: https://billthefarmer.github.io/buses/
languageCode: en-gb

title: Buses
copyright: Copyright &copy; 2021 Bill Farmer
theme: kraiklyn
publishDir: d:/android/buses/docs
metaDataFormat: yaml

params:
  logo:
    - image: images/icon.png
      link: https://github.com/billthefarmer/buses
      width: 25%
    - image: https://img.shields.io/github/v/release/billthefarmer/buses.svg?logo=github
      link: https://github.com/billthefarmer/buses/releases
  sidebarColor: cyan
  customCss:
      - css/custom.css

