baseURL: https://billthefarmer.github.io/diary/
languageCode: en-gb

title: Diary
copyright: Copyright &copy; 2020 Bill Farmer
theme: kraiklyn
publishDir: d:/android/diary/docs
metaDataFormat: yaml

params:
  logo:
    - image: images/Icon.png
      link: https://github.com/billthefarmer/diary
      width: 25%
    - image: https://f-droid.org/wiki/images/c/ca/F-Droid-button_available-on_smaller.png
      link: https://f-droid.org/packages/org.billthefarmer.diary
    - image: https://img.shields.io/github/v/release/billthefarmer/diary.svg?logo=github
      link: https://github.com/billthefarmer/diary/releases
  sidebarColor: cyan
  customCss:
      - css/custom.css
