baseURL: https://billthefarmer.github.io/diary/
languageCode: en-gb

title: Diary
copyright: Copyright &copy; 2006 Bill Farmer
theme: kraiklyn
publishDir: d:/android/diary/docs
metaDataFormat: yaml
markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true

params:
  logo:
    - image: images/Icon.png
      link: https://github.com/billthefarmer/diary
      width: 25%
    - image: https://fdroid.gitlab.io/artwork/badge/get-it-on.svg
      width: 40%
      link: https://f-droid.org/packages/org.billthefarmer.diary
    - image: https://img.shields.io/github/v/release/billthefarmer/diary.svg?logo=github
      link: https://github.com/billthefarmer/diary/releases
  sidebarColor: cyan
  customCss:
      - css/custom.css
  math: true
