baseURL: https://billthefarmer.github.io/specie/
languageCode: en-gb

title: Specie
copyright: Copyright &copy; 2006 Bill Farmer
theme: kraiklyn
publishDir: d:/android/specie/docs
metaDataFormat: yaml

params:
  logo:
    - image: images/icon.png
      link: https://github.com/billthefarmer/specie
      width: 25%
    - image: https://fdroid.gitlab.io/artwork/badge/get-it-on.svg
      width: 40%
      link: https://f-droid.org/packages/org.billthefarmer.specie
    - image: https://img.shields.io/github/v/release/billthefarmer/specie.svg?logo=github
      link: https://github.com/billthefarmer/specie/releases
  sidebarColor: cyan
  customCss:
      - css/custom.css
