baseURL: https://billthefarmer.github.io/print/
languageCode: en-gb

title: Print
copyright: Copyright &copy; 2021 Bill Farmer
theme: kraiklyn
publishDir: d:/android/print/docs
metaDataFormat: yaml

params:
  logo:
    - image: images/icon.png
      link: https://github.com/billthefarmer/print
      width: 25%
#    - image: https://f-droid.org/wiki/images/c/ca/F-Droid-button_available-on_smaller.png
#      link: https://f-droid.org/packages/org.billthefarmer.print
    - image: https://img.shields.io/github/v/release/billthefarmer/print.svg?logo=github
      link: https://github.com/billthefarmer/print/releases
  sidebarColor: cyan
  customCss:
      - css/custom.css

