baseURL: https://billthefarmer.github.io/
languageCode: en-gb
title: Bill Farmer
theme: hugo-strata-theme
publishDir: d:/billthefarmer.github.io/

menu:
  main:
    - name: Blog
      url: https://billthefarmer.github.io/blog
      weight: 10
    - name: Audio Tools
      url: https://billthefarmer.github.io/audiotools
      weight: 20
    - name: Currency
      url: https://billthefarmer.github.io/currency
      weight: 30
    - name: Diary
      url: https://billthefarmer.github.io/diary
      weight: 40
    - name: Editor
      url: https://billthefarmer.github.io/editor
      weight: 50
    - name: Notes
      url: https://billthefarmer.github.io/notes
      weight: 60
    - name: Tuner
      url: https://billthefarmer.github.io/ctuner
      weight: 70
    - name: Gurgle
      url: https://billthefarmer.github.io/gurgle
      weight: 80
    - name: Gridle
      url: https://billthefarmer.github.io/gridle
      weight: 80
    - name: Print
      url: https://billthefarmer.github.io/print
      weight: 90

params:
  date_format: Monday January 2nd 2006
  avatar:
    hide: true
  rss:
    hide: true
  custom_css:
    - css/sidebar.css

  name: Bill Farmer
  description: Home page

  sidebar:
    github: billthefarmer
    gitlab: williamjfarmer
    copyright:
      - Copyright &copy; 2006 Bill Farmer

  sharingicons:
    hide: true

  about:
    hide: false
    title: Bill Farmer
    image: /images/20131726.jpg
    content:
      I am retired, a morris musician and an itinerant developer. I
      was a chartered electrical engineer. Over the course of a long
      career working for the local electrick light company I developed
      various bits and pieces of software in so many different
      languages I can no longer remember them all.

  portfolio:
    hide: false
    title: Recent projects
    links:
    - title: Gridle
      url: https://github.com/billthefarmer/gridle
      description: Android simple word game
    - title: Gurgle
      url: https://github.com/billthefarmer/gurgle
      description: Android simple word game
    - title: Specie
      url: https://github.com/billthefarmer/specie
      description: Android currency converter
    - title: Buses
      url: https://github.com/billthefarmer/buses
      description: Android GB bus times
    - title: Print
      url: https://github.com/billthefarmer/print
      description: Android print utility
    - title: Notes
      url: https://github.com/billthefarmer/notes
      description: Android notebook
    - title: Diary
      url: https://github.com/billthefarmer/diary
      description: Android diary
    - title: Tuner
      url: https://github.com/billthefarmer/tuner
      description: Android tuner
    - title: Editor
      url: https://github.com/billthefarmer/editor
      description: Android text editor
    - title: Currency
      url: https://github.com/billthefarmer/currency
      description: Android currency converter
    - title: Crossword
      url: https://github.com/billthefarmer/crossword
      description: Android crossword solver
    - title: Melodeon
      url: https://github.com/billthefarmer/melodeon
      description: Android melodeon
    - title: Accordion
      url: https://github.com/billthefarmer/accordion
      description: Android accordion
    - title: Mididriver
      url: https://github.com/billthefarmer/mididriver
      description: Android mididriver
    - title: Oscilloscope
      url: https://github.com/billthefarmer/scope
      description: Android oscilloscope
    - title: Signal Generator
      url: https://github.com/billthefarmer/sig-gen
      description: Android signal generator
    - title: Custom Calendar View
      url: https://github.com/billthefarmer/customcalendarview
      description: Android custom calendar view
    - title: Intent Radio Shortcut creator
      url: https://github.com/billthefarmer/shorty
      description: Android intent radio shortcut creator
    - title: FFTS
      url: https://github.com/billthefarmer/ffts-android
      description: Android FFTS (Fastest Fourier Transform in the South)
    - title: GPDF
      url: https://github.com/billthefarmer/gpdf
      description: Genealogy pdf chart creation
    - title: Tuner
      url: https://github.com/billthefarmer/c-tuner
      description: Tuner for Windows and Mac
    - title: Audio Tools
      url: https://github.com/billthefarmer/audiotools
      description: Scope, Sig Gen, LMS and SLMS for Windows and Mac
    - title: Accordion
      url: https://github.com/billthefarmer/c-accordion
      description: Accordion for Windows and Mac
    - title: Melodeon
      url: https://github.com/billthefarmer/c-melodeon
      description: Melodeon for Windows and Mac
    - title: What-o-Clock
      url: https://github.com/billthefarmer/what-o-clock
      description: Extremely useful clock display
    - title: Whatever-o-Meter
      url: https://github.com/billthefarmer/whatever-o-meter
      description: Wordpress and Hugo plugin for creating a whatever-o-meter

  recentposts:
    hide: true

  contact:
    hide: true
