baseURL: https://billthefarmer.github.io/ctuner/
languageCode: en-gb

title: Tuner
copyright: Copyright &copy; 2018 Bill Farmer
theme: kraiklyn
publishDir: d:/c/github/ctuner/docs
metaDataFormat: yaml

params:
  sidebarColor: cyan
  customCss:
      - css/custom.css
