baseURL: https://billthefarmer.github.io/gridle/
languageCode: en-gb

title: Gridle
copyright: Copyright &copy; 2006 Bill Farmer
theme: kraiklyn
publishDir: d:/android/gridle/docs
metaDataFormat: yaml

params:
  logo:
    - image: images/icon.png
      link: https://github.com/billthefarmer/gridle
      width: 25%
    - image: https://fdroid.gitlab.io/artwork/badge/get-it-on.svg
      link: https://f-droid.org/packages/org.billthefarmer.gridle
      width: 40%
    - image: https://img.shields.io/github/v/release/billthefarmer/gridle.svg?logo=github
      link: https://github.com/billthefarmer/gridle/releases
  sidebarColor: lightgrey
  customCss:
      - css/custom.css
