baseURL: https://billthefarmer.github.io/editor/
languageCode: en-gb

title: Editor
copyright: Copyright &copy; 2020 Bill Farmer
theme: kraiklyn
publishDir: d:/android/editor/docs
metaDataFormat: yaml

params:
  logo:
    - image: images/icon.png
      link: https://github.com/billthefarmer/editor
      width: 25%
    - image: https://f-droid.org/wiki/images/c/ca/F-Droid-button_available-on_smaller.png
      link: https://f-droid.org/packages/org.billthefarmer.editor
    - image: https://img.shields.io/github/v/release/billthefarmer/editor.svg?logo=github
      link: https://github.com/billthefarmer/editor/releases
  sidebarColor: cyan
  customCss:
      - css/custom.css
