baseURL: https://billthefarmer.github.io/editor/
languageCode: en-gb

title: Editor
copyright: Copyright &copy; 2021 Bill Farmer
theme: kraiklyn
publishDir: d:/android/editor/docs
metaDataFormat: yaml

params:
  logo:
    - image: images/icon.png
      link: https://github.com/billthefarmer/editor
      width: 25%
    - image: https://fdroid.gitlab.io/artwork/badge/get-it-on.svg
      width: 40%
      link: https://f-droid.org/packages/org.billthefarmer.editor
    - image: https://img.shields.io/github/v/release/billthefarmer/editor.svg?logo=github
      link: https://github.com/billthefarmer/editor/releases
  sidebarColor: cyan
  customCss:
      - css/custom.css
