baseURL: https://billthefarmer.github.io/blog/
languageCode: en-gb
title: Bill Farmer
copyright: Copyright &copy; 2019 Bill Farmer
theme: theme-hugo-foundation6
publishDir: d:/billthefarmer.github.io/blog/
metaDataFormat: yaml
pygmentsCodeFences: true
pygmentsStyle: emacs

# number of posts to show on home/category/tag pages (Default: 10)
paginate: 5

taxonomies:
  category: categories

related:
  threshold: 10
  includeNewer: true
  indices:
    - name: keywords
      weight: 80

menu:
  sidebar:
    - name: Home
      url: http://billthefarmer.github.io
    - name: Github
      url: https://github.com/billthefarmer
    - name: Gitlab
      url: https://gitlab.com/williamjfarmer

params:
  description: Random thoughts on random subjects
  header_background: images/2013/12/cropped-P1010089.jpg
  # cookie_consent_info_url: http://cookiesandyou.com
  sidebar:
    # Optional about block for sidebar (can be Markdown)
    # about: "Bill Farmer's Blog"
    num_recent_posts: 10
  sharingicons:
    hide: true
