baseURL: http://example.org/
languageCode: en-gb

title: Notes
copyright: Copyright &copy; 2020 Bill Farmer
theme: kraiklyn
publishDir: d:/c/github/notes/docs
metaDataFormat: yaml

params:
  sidebarColor: cyan
  customCss:
      - css/custom.css
