baseURL: https://billthefarmer.github.io/notes/
languageCode: en-gb

title: Notes
copyright: Copyright &copy; 2020 Bill Farmer
theme: kraiklyn
publishDir: d:/android/notes/docs
metaDataFormat: yaml

params:
  logo:
    - image: images/Icon.png
      link: https://github.com/billthefarmer/notes
      width: 25%
    - image: https://f-droid.org/wiki/images/c/ca/F-Droid-button_available-on_smaller.png
      link: https://f-droid.org/packages/org.billthefarmer.notes
    - image: https://img.shields.io/github/v/release/billthefarmer/notes.svg?logo=github
      link: https://github.com/billthefarmer/notes/releases
  sidebarColor: cyan
  customCss:
      - css/custom.css
