baseURL: https://billthefarmer.github.io/notes/
languageCode: en-gb

title: Notes
copyright: Copyright &copy; 2021 Bill Farmer
theme: kraiklyn
publishDir: d:/android/notes/docs
metaDataFormat: yaml

params:
  logo:
    - image: images/Icon.png
      link: https://github.com/billthefarmer/notes
      width: 25%
    - image: https://fdroid.gitlab.io/artwork/badge/get-it-on.svg
      width: 40%
      link: https://f-droid.org/packages/org.billthefarmer.notes
    - image: https://img.shields.io/github/v/release/billthefarmer/notes.svg?logo=github
      link: https://github.com/billthefarmer/notes/releases
  sidebarColor: cyan
  customCss:
      - css/custom.css
