baseURL: https://billthefarmer.github.io/notes/
languageCode: en-gb

title: Notes
copyright: Copyright &copy; 2020 Bill Farmer
theme: kraiklyn
publishDir: d:/android/notes/docs
metaDataFormat: yaml

params:
  sidebarColor: cyan
  customCss:
      - css/custom.css
