baseURL: https://billthefarmer.github.io/currency/
languageCode: en-gb

title: Currency
copyright: Copyright &copy; 2021 Bill Farmer
theme: kraiklyn
publishDir: d:/android/currency/docs
metaDataFormat: yaml

params:
  logo:
    - image: images/icon.png
      link: https://github.com/billthefarmer/currency
      width: 25%
    - image: https://f-droid.org/wiki/images/c/ca/F-Droid-button_available-on_smaller.png
      link: https://f-droid.org/packages/org.billthefarmer.currency
    - image: https://img.shields.io/github/v/release/billthefarmer/currency.svg?logo=github
      link: https://github.com/billthefarmer/currency/releases
  sidebarColor: cyan
  customCss:
      - css/custom.css
