baseURL: https://billthefarmer.github.io/audiotools/
languageCode: en-gb
title: Audiotools
copyright: Copyright &copy; 2019 Bill Farmer
theme: kraiklyn
publishDir: d:/c/github/audiotools/docs
metaDataFormat: yaml

params:
  sidebarColor: cyan
  customCss:
      - css/custom.css
